index:
    path: /
    controller: App\Controller\SecurityController::login

projekcije:
    path: /projekcija
    controller: App\Controller\ProjekcijaController::index

odabir:
    path: /projekcija/odabir
    controller: App\Controller\ProjekcijaController::indexx